import { Injectable } from '@angular/core';

@Injectable()
export class EmployeeService {
  getEmployeesData() {
    return [
      {
        id: '1',
        username: 'andrewtate',
        firstName: 'Andrew',
        lastName: 'Tate',
        email: 'andrewtate@gmail.com',
        birthDate: '2000-12-05',
        basicSalary: 30000000,
        status: 'Intern',
        group: 'Mandiri Group',
        description: 'New Employee',
      },
      {
        id: '2',
        username: 'brandonSalim',
        firstName: 'Brandon',
        lastName: 'Salim',
        email: 'brandonsalim@gmail.com',
        birthDate: ' 2023-11-10',
        basicSalary: 30000000,
        status: 'Fixed',
        group: 'BCA Group',
        description: '10 years experience',
      },
      {
        id: '3',
        username: 'christinaLaurentia',
        firstName: 'Christina',
        lastName: 'Laurentia',
        email: 'christinalaurentia@gmail.com',
        birthDate: '1990-02-02',
        basicSalary: 30000000,
        status: 'Intern',
        group: 'BNI Group',
        description: '5 years experience',
      },
      {
        id: '4',
        username: 'elenaGilbert',
        firstName: 'Elena',
        lastName: 'Gilbert',
        email: 'elenagilbert@gmail.com',
        birthDate: '1992-02-02',
        basicSalary: 30000000,
        status: 'Fixed',
        group: 'BSI Group',
        description: '20 years experience',
      },
      {
        id: '5',
        username: 'user5',
        firstName: 'First5',
        lastName: 'Last5',
        email: 'user5@example.com',
        birthDate: '1993-03-03',
        basicSalary: 35000000,
        status: 'Intern',
        group: 'Group A',
        description: 'Some description',
      },
      {
        id: '6',
        username: 'user6',
        firstName: 'First6',
        lastName: 'Last6',
        email: 'user6@example.com',
        birthDate: '1994-04-04',
        basicSalary: 36000000,
        status: 'Fixed',
        group: 'Group B',
        description: 'Another description',
      },
      {
        id: '7',
        username: 'user7',
        firstName: 'First7',
        lastName: 'Last7',
        email: 'user7@example.com',
        birthDate: '1995-05-05',
        basicSalary: 37000000,
        status: 'Intern',
        group: 'Group C',
        description: 'More description',
      },
      {
        id: '8',
        username: 'user8',
        firstName: 'First8',
        lastName: 'Last8',
        email: 'user8@example.com',
        birthDate: '1996-06-06',
        basicSalary: 38000000,
        status: 'Intern',
        group: 'Group D',
        description: 'Additional description',
      },
      {
        id: '9',
        username: 'user9',
        firstName: 'First9',
        lastName: 'Last9',
        email: 'user9@example.com',
        birthDate: '1997-07-07',
        basicSalary: 39000000,
        status: 'Fixed',
        group: 'Group E',
        description: 'Extra description',
      },
      {
        id: '10',
        username: 'user10',
        firstName: 'First10',
        lastName: 'Last10',
        email: 'user10@example.com',
        birthDate: '1998-08-08',
        basicSalary: 40000000,
        status: 'Intern',
        group: 'Group F',
        description: 'Yet more description',
      },
      {
        id: '11',
        username: 'user11',
        firstName: 'First11',
        lastName: 'Last11',
        email: 'user11@example.com',
        birthDate: '1999-09-09',
        basicSalary: 41000000,
        status: 'Fixed',
        group: 'Group G',
        description: 'Description 11',
      },
      {
        id: '12',
        username: 'user12',
        firstName: 'First12',
        lastName: 'Last12',
        email: 'user12@example.com',
        birthDate: '2000-10-10',
        basicSalary: 42000000,
        status: 'Intern',
        group: 'Group H',
        description: 'Description 12',
      },
      {
        id: '13',
        username: 'user13',
        firstName: 'First13',
        lastName: 'Last13',
        email: 'user13@example.com',
        birthDate: '2001-11-11',
        basicSalary: 43000000,
        status: 'Fixed',
        group: 'Group I',
        description: 'Description 13',
      },
      {
        id: '14',
        username: 'user14',
        firstName: 'First14',
        lastName: 'Last14',
        email: 'user14@example.com',
        birthDate: '2002-12-12',
        basicSalary: 44000000,
        status: 'Intern',
        group: 'Group J',
        description: 'Description 14',
      },
      {
        id: '15',
        username: 'user15',
        firstName: 'First15',
        lastName: 'Last15',
        email: 'user15@example.com',
        birthDate: '2003-01-01',
        basicSalary: 45000000,
        status: 'Intern',
        group: 'Group K',
        description: 'Description 15',
      },
      {
        id: '16',
        username: 'user16',
        firstName: 'First16',
        lastName: 'Last16',
        email: 'user16@example.com',
        birthDate: '2004-02-02',
        basicSalary: 46000000,
        status: 'Fixed',
        group: 'Group L',
        description: 'Description 16',
      },
      {
        id: '17',
        username: 'user17',
        firstName: 'First17',
        lastName: 'Last17',
        email: 'user17@example.com',
        birthDate: '2005-03-03',
        basicSalary: 47000000,
        status: 'Intern',
        group: 'Group M',
        description: 'Description 17',
      },
      {
        id: '18',
        username: 'user18',
        firstName: 'First18',
        lastName: 'Last18',
        email: 'user18@example.com',
        birthDate: '2006-04-04',
        basicSalary: 48000000,
        status: 'Fixed',
        group: 'Group N',
        description: 'Description 18',
      },
      {
        id: '19',
        username: 'user19',
        firstName: 'First19',
        lastName: 'Last19',
        email: 'user19@example.com',
        birthDate: '2007-05-05',
        basicSalary: 49000000,
        status: 'Intern',
        group: 'Group O',
        description: 'Description 19',
      },
      {
        id: '20',
        username: 'user20',
        firstName: 'First20',
        lastName: 'Last20',
        email: 'user20@example.com',
        birthDate: '2008-06-06',
        basicSalary: 50000000,
        status: 'Fixed',
        group: 'Group P',
        description: 'Description 20',
      },
      {
        id: '20',
        username: 'user20',
        firstName: 'First20',
        lastName: 'Last20',
        email: 'user20@example.com',
        birthDate: '2008-06-06',
        basicSalary: 50000000,
        status: 'Fixed',
        group: 'Group P',
        description: 'Description 20',
      },
      {
        id: '21',
        username: 'user21',
        firstName: 'First21',
        lastName: 'Last21',
        email: 'user21@example.com',
        birthDate: '2009-07-07',
        basicSalary: 51000000,
        status: 'Intern',
        group: 'Group Q',
        description: 'Description 21',
      },
      {
        id: '22',
        username: 'user22',
        firstName: 'First22',
        lastName: 'Last22',
        email: 'user22@example.com',
        birthDate: '2010-08-08',
        basicSalary: 52000000,
        status: 'Fixed',
        group: 'Group R',
        description: 'Description 22',
      },
      {
        id: '23',
        username: 'user23',
        firstName: 'First23',
        lastName: 'Last23',
        email: 'user23@example.com',
        birthDate: '2011-09-09',
        basicSalary: 53000000,
        status: 'Intern',
        group: 'Group S',
        description: 'Description 23',
      },
      {
        id: '24',
        username: 'user24',
        firstName: 'First24',
        lastName: 'Last24',
        email: 'user24@example.com',
        birthDate: '2012-10-10',
        basicSalary: 54000000,
        status: 'Fixed',
        group: 'Group T',
        description: 'Description 24',
      },
      {
        id: '25',
        username: 'user25',
        firstName: 'First25',
        lastName: 'Last25',
        email: 'user25@example.com',
        birthDate: '2013-11-11',
        basicSalary: 55000000,
        status: 'Intern',
        group: 'Group U',
        description: 'Description 25',
      },
      {
        id: '26',
        username: 'user26',
        firstName: 'First26',
        lastName: 'Last26',
        email: 'user26@example.com',
        birthDate: '2014-12-12',
        basicSalary: 56000000,
        status: 'Fixed',
        group: 'Group V',
        description: 'Description 26',
      },
      {
        id: '27',
        username: 'user27',
        firstName: 'First27',
        lastName: 'Last27',
        email: 'user27@example.com',
        birthDate: '2015-01-01',
        basicSalary: 57000000,
        status: 'Intern',
        group: 'Group W',
        description: 'Description 27',
      },
      {
        id: '28',
        username: 'user28',
        firstName: 'First28',
        lastName: 'Last28',
        email: 'user28@example.com',
        birthDate: '2016-02-02',
        basicSalary: 58000000,
        status: 'Fixed',
        group: 'Group X',
        description: 'Description 28',
      },
      {
        id: '29',
        username: 'user29',
        firstName: 'First29',
        lastName: 'Last29',
        email: 'user29@example.com',
        birthDate: '2017-03-03',
        basicSalary: 59000000,
        status: 'Intern',
        group: 'Group Y',
        description: 'Description 29',
      },
      {
        id: '30',
        username: 'user30',
        firstName: 'First30',
        lastName: 'Last30',
        email: 'user30@example.com',
        birthDate: '2018-04-04',
        basicSalary: 60000000,
        status: 'Fixed',
        group: 'Group Z',
        description: 'Description 30',
      },
      {
        id: '31',
        username: 'user31',
        firstName: 'First31',
        lastName: 'Last31',
        email: 'user31@example.com',
        birthDate: '2019-05-05',
        basicSalary: 61000000,
        status: 'Intern',
        group: 'Group AA',
        description: 'Description 31',
      },
      {
        id: '32',
        username: 'user32',
        firstName: 'First32',
        lastName: 'Last32',
        email: 'user32@example.com',
        birthDate: '2020-06-06',
        basicSalary: 62000000,
        status: 'Fixed',
        group: 'Group BB',
        description: 'Description 32',
      },
      {
        id: '33',
        username: 'user33',
        firstName: 'First33',
        lastName: 'Last33',
        email: 'user33@example.com',
        birthDate: '2021-07-07',
        basicSalary: 63000000,
        status: 'Intern',
        group: 'Group CC',
        description: 'Description 33',
      },
      {
        id: '34',
        username: 'user34',
        firstName: 'First34',
        lastName: 'Last34',
        email: 'user34@example.com',
        birthDate: '2022-08-08',
        basicSalary: 64000000,
        status: 'Fixed',
        group: 'Group DD',
        description: 'Description 34',
      },
      {
        id: '35',
        username: 'user35',
        firstName: 'First35',
        lastName: 'Last35',
        email: 'user35@example.com',
        birthDate: '2023-09-09',
        basicSalary: 65000000,
        status: 'Intern',
        group: 'Group EE',
        description: 'Description 35',
      },
      {
        id: '36',
        username: 'user36',
        firstName: 'First36',
        lastName: 'Last36',
        email: 'user36@example.com',
        birthDate: '2024-10-10',
        basicSalary: 66000000,
        status: 'Fixed',
        group: 'Group FF',
        description: 'Description 36',
      },
      {
        id: '37',
        username: 'user37',
        firstName: 'First37',
        lastName: 'Last37',
        email: 'user37@example.com',
        birthDate: '2025-11-11',
        basicSalary: 67000000,
        status: 'Intern',
        group: 'Group GG',
        description: 'Description 37',
      },
      {
        id: '38',
        username: 'user38',
        firstName: 'First38',
        lastName: 'Last38',
        email: 'user38@example.com',
        birthDate: '2026-12-12',
        basicSalary: 68000000,
        status: 'Fixed',
        group: 'Group HH',
        description: 'Description 38',
      },
      {
        id: '39',
        username: 'user39',
        firstName: 'First39',
        lastName: 'Last39',
        email: 'user39@example.com',
        birthDate: '2027-01-01',
        basicSalary: 69000000,
        status: 'Intern',
        group: 'Group II',
        description: 'Description 39',
      },
      {
        id: '40',
        username: 'user40',
        firstName: 'First40',
        lastName: 'Last40',
        email: 'user40@example.com',
        birthDate: '2028-02-02',
        basicSalary: 70000000,
        status: 'Fixed',
        group: 'Group JJ',
        description: 'Description 40',
      },
      {
        id: '41',
        username: 'user41',
        firstName: 'First41',
        lastName: 'Last41',
        email: 'user41@example.com',
        birthDate: '2029-03-03',
        basicSalary: 71000000,
        status: 'Intern',
        group: 'Group KK',
        description: 'Description 41',
      },
      {
        id: '42',
        username: 'user42',
        firstName: 'First42',
        lastName: 'Last42',
        email: 'user42@example.com',
        birthDate: '2030-04-04',
        basicSalary: 72000000,
        status: 'Fixed',
        group: 'Group LL',
        description: 'Description 42',
      },
      {
        id: '43',
        username: 'user43',
        firstName: 'First43',
        lastName: 'Last43',
        email: 'user43@example.com',
        birthDate: '2031-05-05',
        basicSalary: 73000000,
        status: 'Intern',
        group: 'Group MM',
        description: 'Description 43',
      },
      {
        id: '44',
        username: 'user44',
        firstName: 'First44',
        lastName: 'Last44',
        email: 'user44@example.com',
        birthDate: '2032-06-06',
        basicSalary: 74000000,
        status: 'Fixed',
        group: 'Group NN',
        description: 'Description 44',
      },
      {
        id: '45',
        username: 'user45',
        firstName: 'First45',
        lastName: 'Last45',
        email: 'user45@example.com',
        birthDate: '2033-07-07',
        basicSalary: 75000000,
        status: 'Intern',
        group: 'Group OO',
        description: 'Description 45',
      },
      {
        id: '46',
        username: 'user46',
        firstName: 'First46',
        lastName: 'Last46',
        email: 'user46@example.com',
        birthDate: '2034-08-08',
        basicSalary: 76000000,
        status: 'Fixed',
        group: 'Group PP',
        description: 'Description 46',
      },
      {
        id: '47',
        username: 'user47',
        firstName: 'First47',
        lastName: 'Last47',
        email: 'user47@example.com',
        birthDate: '2035-09-09',
        basicSalary: 77000000,
        status: 'Intern',
        group: 'Group QQ',
        description: 'Description 47',
      },
      {
        id: '48',
        username: 'user48',
        firstName: 'First48',
        lastName: 'Last48',
        email: 'user48@example.com',
        birthDate: '2036-10-10',
        basicSalary: 78000000,
        status: 'Fixed',
        group: 'Group RR',
        description: 'Description 48',
      },
      {
        id: '49',
        username: 'user49',
        firstName: 'First49',
        lastName: 'Last49',
        email: 'user49@example.com',
        birthDate: '2037-11-11',
        basicSalary: 79000000,
        status: 'Intern',
        group: 'Group SS',
        description: 'Description 49',
      },
      {
        id: '50',
        username: 'user50',
        firstName: 'First50',
        lastName: 'Last50',
        email: 'user50@example.com',
        birthDate: '2038-12-12',
        basicSalary: 80000000,
        status: 'Fixed',
        group: 'Group TT',
        description: 'Description 50',
      },
      {
        id: '51',
        username: 'user51',
        firstName: 'First51',
        lastName: 'Last51',
        email: 'user51@example.com',
        birthDate: '2039-01-01',
        basicSalary: 81000000,
        status: 'Intern',
        group: 'Group UU',
        description: 'Description 51',
      },
      {
        id: '52',
        username: 'user52',
        firstName: 'First52',
        lastName: 'Last52',
        email: 'user52@example.com',
        birthDate: '2040-02-02',
        basicSalary: 82000000,
        status: 'Fixed',
        group: 'Group VV',
        description: 'Description 52',
      },
      {
        id: '53',
        username: 'user53',
        firstName: 'First53',
        lastName: 'Last53',
        email: 'user53@example.com',
        birthDate: '2041-03-03',
        basicSalary: 83000000,
        status: 'Intern',
        group: 'Group WW',
        description: 'Description 53',
      },
      {
        id: '54',
        username: 'user54',
        firstName: 'First54',
        lastName: 'Last54',
        email: 'user54@example.com',
        birthDate: '2042-04-04',
        basicSalary: 84000000,
        status: 'Fixed',
        group: 'Group XX',
        description: 'Description 54',
      },
      {
        id: '55',
        username: 'user55',
        firstName: 'First55',
        lastName: 'Last55',
        email: 'user55@example.com',
        birthDate: '2043-05-05',
        basicSalary: 85000000,
        status: 'Intern',
        group: 'Group YY',
        description: 'Description 55',
      },
      {
        id: '56',
        username: 'user56',
        firstName: 'First56',
        lastName: 'Last56',
        email: 'user56@example.com',
        birthDate: '2044-06-06',
        basicSalary: 86000000,
        status: 'Fixed',
        group: 'Group ZZ',
        description: 'Description 56',
      },
      {
        id: '57',
        username: 'user57',
        firstName: 'First57',
        lastName: 'Last57',
        email: 'user57@example.com',
        birthDate: '2045-07-07',
        basicSalary: 87000000,
        status: 'Intern',
        group: 'Group AAA',
        description: 'Description 57',
      },
      {
        id: '58',
        username: 'user58',
        firstName: 'First58',
        lastName: 'Last58',
        email: 'user58@example.com',
        birthDate: '2046-08-08',
        basicSalary: 88000000,
        status: 'Fixed',
        group: 'Group BBB',
        description: 'Description 58',
      },
      {
        id: '59',
        username: 'user59',
        firstName: 'First59',
        lastName: 'Last59',
        email: 'user59@example.com',
        birthDate: '2047-09-09',
        basicSalary: 89000000,
        status: 'Intern',
        group: 'Group CCC',
        description: 'Description 59',
      },
      {
        id: '60',
        username: 'user60',
        firstName: 'First60',
        lastName: 'Last60',
        email: 'user60@example.com',
        birthDate: '2048-10-10',
        basicSalary: 90000000,
        status: 'Fixed',
        group: 'Group DDD',
        description: 'Description 60',
      },
      {
        id: '61',
        username: 'user61',
        firstName: 'First61',
        lastName: 'Last61',
        email: 'user61@example.com',
        birthDate: '2049-11-11',
        basicSalary: 91000000,
        status: 'Intern',
        group: 'Group EEE',
        description: 'Description 61',
      },
      {
        id: '62',
        username: 'user62',
        firstName: 'First62',
        lastName: 'Last62',
        email: 'user62@example.com',
        birthDate: '2050-12-12',
        basicSalary: 92000000,
        status: 'Fixed',
        group: 'Group FFF',
        description: 'Description 62',
      },
      {
        id: '63',
        username: 'user63',
        firstName: 'First63',
        lastName: 'Last63',
        email: 'user63@example.com',
        birthDate: '2051-01-01',
        basicSalary: 93000000,
        status: 'Intern',
        group: 'Group GGG',
        description: 'Description 63',
      },
      {
        id: '64',
        username: 'user64',
        firstName: 'First64',
        lastName: 'Last64',
        email: 'user64@example.com',
        birthDate: '2052-02-02',
        basicSalary: 94000000,
        status: 'Fixed',
        group: 'Group HHH',
        description: 'Description 64',
      },
      {
        id: '65',
        username: 'user65',
        firstName: 'First65',
        lastName: 'Last65',
        email: 'user65@example.com',
        birthDate: '2053-03-03',
        basicSalary: 95000000,
        status: 'Intern',
        group: 'Group III',
        description: 'Description 65',
      },
      {
        id: '66',
        username: 'user66',
        firstName: 'First66',
        lastName: 'Last66',
        email: 'user66@example.com',
        birthDate: '2054-04-04',
        basicSalary: 96000000,
        status: 'Fixed',
        group: 'Group JJJ',
        description: 'Description 66',
      },
      {
        id: '67',
        username: 'user67',
        firstName: 'First67',
        lastName: 'Last67',
        email: 'user67@example.com',
        birthDate: '2055-05-05',
        basicSalary: 97000000,
        status: 'Intern',
        group: 'Group KKK',
        description: 'Description 67',
      },
      {
        id: '68',
        username: 'user68',
        firstName: 'First68',
        lastName: 'Last68',
        email: 'user68@example.com',
        birthDate: '2056-06-06',
        basicSalary: 98000000,
        status: 'Fixed',
        group: 'Group LLL',
        description: 'Description 68',
      },
      {
        id: '69',
        username: 'user69',
        firstName: 'First69',
        lastName: 'Last69',
        email: 'user69@example.com',
        birthDate: '2057-07-07',
        basicSalary: 99000000,
        status: 'Intern',
        group: 'Group MMM',
        description: 'Description 69',
      },
      {
        id: '70',
        username: 'user70',
        firstName: 'First70',
        lastName: 'Last70',
        email: 'user70@example.com',
        birthDate: '2058-08-08',
        basicSalary: 100000000,
        status: 'Fixed',
        group: 'Group NNN',
        description: 'Description 70',
      },
      {
        id: '71',
        username: 'user71',
        firstName: 'First71',
        lastName: 'Last71',
        email: 'user71@example.com',
        birthDate: '2059-11-11',
        basicSalary: 101000000,
        status: 'Intern',
        group: 'Group YYY',
        description: 'Description 71',
      },
      {
        id: '72',
        username: 'user72',
        firstName: 'First72',
        lastName: 'Last72',
        email: 'user72@example.com',
        birthDate: '2060-12-12',
        basicSalary: 102000000,
        status: 'Fixed',
        group: 'Group ZZZ',
        description: 'Description 72',
      },
      {
        id: '73',
        username: 'user73',
        firstName: 'First73',
        lastName: 'Last73',
        email: 'user73@example.com',
        birthDate: '2061-01-01',
        basicSalary: 103000000,
        status: 'Intern',
        group: 'Group AAAA',
        description: 'Description 73',
      },
      {
        id: '74',
        username: 'user74',
        firstName: 'First74',
        lastName: 'Last74',
        email: 'user74@example.com',
        birthDate: '2062-02-02',
        basicSalary: 104000000,
        status: 'Fixed',
        group: 'Group BBBB',
        description: 'Description 74',
      },
      {
        id: '75',
        username: 'user75',
        firstName: 'First75',
        lastName: 'Last75',
        email: 'user75@example.com',
        birthDate: '2063-03-03',
        basicSalary: 105000000,
        status: 'Intern',
        group: 'Group CCCC',
        description: 'Description 75',
      },
      {
        id: '76',
        username: 'user76',
        firstName: 'First76',
        lastName: 'Last76',
        email: 'user76@example.com',
        birthDate: '2064-04-04',
        basicSalary: 106000000,
        status: 'Fixed',
        group: 'Group DDDD',
        description: 'Description 76',
      },
      {
        id: '77',
        username: 'user77',
        firstName: 'First77',
        lastName: 'Last77',
        email: 'user77@example.com',
        birthDate: '2065-05-05',
        basicSalary: 107000000,
        status: 'Intern',
        group: 'Group EEEE',
        description: 'Description 77',
      },
      {
        id: '78',
        username: 'user78',
        firstName: 'First78',
        lastName: 'Last78',
        email: 'user78@example.com',
        birthDate: '2066-06-06',
        basicSalary: 108000000,
        status: 'Fixed',
        group: 'Group FFFF',
        description: 'Description 78',
      },
      {
        id: '79',
        username: 'user79',
        firstName: 'First79',
        lastName: 'Last79',
        email: 'user79@example.com',
        birthDate: '2067-07-07',
        basicSalary: 109000000,
        status: 'Intern',
        group: 'Group GGGG',
        description: 'Description 79',
      },
      {
        id: '80',
        username: 'user80',
        firstName: 'First80',
        lastName: 'Last80',
        email: 'user80@example.com',
        birthDate: '2068-08-08',
        basicSalary: 110000000,
        status: 'Fixed',
        group: 'Group HHHH',
        description: 'Description 80',
      },
      {
        id: '81',
        username: 'user81',
        firstName: 'First81',
        lastName: 'Last81',
        email: 'user81@example.com',
        birthDate: '2069-09-09',
        basicSalary: 111000000,
        status: 'Intern',
        group: 'Group IIII',
        description: 'Description 81',
      },
      {
        id: '82',
        username: 'user82',
        firstName: 'First82',
        lastName: 'Last82',
        email: 'user82@example.com',
        birthDate: '2070-10-10',
        basicSalary: 112000000,
        status: 'Fixed',
        group: 'Group JJJJ',
        description: 'Description 82',
      },
      {
        id: '83',
        username: 'user83',
        firstName: 'First83',
        lastName: 'Last83',
        email: 'user83@example.com',
        birthDate: '2071-11-11',
        basicSalary: 113000000,
        status: 'Intern',
        group: 'Group KKKK',
        description: 'Description 83',
      },
      {
        id: '84',
        username: 'user84',
        firstName: 'First84',
        lastName: 'Last84',
        email: 'user84@example.com',
        birthDate: '2072-12-12',
        basicSalary: 114000000,
        status: 'Fixed',
        group: 'Group LLLL',
        description: 'Description 84',
      },
      {
        id: '85',
        username: 'user85',
        firstName: 'First85',
        lastName: 'Last85',
        email: 'user85@example.com',
        birthDate: '2073-01-01',
        basicSalary: 115000000,
        status: 'Intern',
        group: 'Group MMMM',
        description: 'Description 85',
      },
      {
        id: '86',
        username: 'user86',
        firstName: 'First86',
        lastName: 'Last86',
        email: 'user86@example.com',
        birthDate: '2074-02-02',
        basicSalary: 116000000,
        status: 'Fixed',
        group: 'Group NNNN',
        description: 'Description 86',
      },
      {
        id: '87',
        username: 'user87',
        firstName: 'First87',
        lastName: 'Last87',
        email: 'user87@example.com',
        birthDate: '2075-03-03',
        basicSalary: 117000000,
        status: 'Intern',
        group: 'Group OOOO',
        description: 'Description 87',
      },
      {
        id: '88',
        username: 'user88',
        firstName: 'First88',
        lastName: 'Last88',
        email: 'user88@example.com',
        birthDate: '2076-04-04',
        basicSalary: 118000000,
        status: 'Fixed',
        group: 'Group PPPP',
        description: 'Description 88',
      },
      {
        id: '89',
        username: 'user89',
        firstName: 'First89',
        lastName: 'Last89',
        email: 'user89@example.com',
        birthDate: '2077-05-05',
        basicSalary: 119000000,
        status: 'Intern',
        group: 'Group QQQQ',
        description: 'Description 89',
      },
      {
        id: '90',
        username: 'user90',
        firstName: 'First90',
        lastName: 'Last90',
        email: 'user90@example.com',
        birthDate: '2078-06-06',
        basicSalary: 120000000,
        status: 'Fixed',
        group: 'Group RRRR',
        description: 'Description 90',
      },
      {
        id: '91',
        username: 'user91',
        firstName: 'First91',
        lastName: 'Last91',
        email: 'user91@example.com',
        birthDate: '2079-07-07',
        basicSalary: 121000000,
        status: 'Intern',
        group: 'Group SSSS',
        description: 'Description 91',
      },
      {
        id: '92',
        username: 'user92',
        firstName: 'First92',
        lastName: 'Last92',
        email: 'user92@example.com',
        birthDate: '2080-08-08',
        basicSalary: 122000000,
        status: 'Fixed',
        group: 'Group TTTT',
        description: 'Description 92',
      },
      {
        id: '93',
        username: 'user93',
        firstName: 'First93',
        lastName: 'Last93',
        email: 'user93@example.com',
        birthDate: '2081-09-09',
        basicSalary: 123000000,
        status: 'Intern',
        group: 'Group UUUU',
        description: 'Description 93',
      },
      {
        id: '94',
        username: 'user94',
        firstName: 'First94',
        lastName: 'Last94',
        email: 'user94@example.com',
        birthDate: '2082-10-10',
        basicSalary: 124000000,
        status: 'Fixed',
        group: 'Group VVVV',
        description: 'Description 94',
      },
      {
        id: '95',
        username: 'user95',
        firstName: 'First95',
        lastName: 'Last95',
        email: 'user95@example.com',
        birthDate: '2083-11-11',
        basicSalary: 125000000,
        status: 'Intern',
        group: 'Group WWWW',
        description: 'Description 95',
      },
      {
        id: '96',
        username: 'user96',
        firstName: 'First96',
        lastName: 'Last96',
        email: 'user96@example.com',
        birthDate: '2084-12-12',
        basicSalary: 126000000,
        status: 'Fixed',
        group: 'Group XXXX',
        description: 'Description 96',
      },
      {
        id: '97',
        username: 'user97',
        firstName: 'First97',
        lastName: 'Last97',
        email: 'user97@example.com',
        birthDate: '2085-01-01',
        basicSalary: 127000000,
        status: 'Intern',
        group: 'Group YYYY',
        description: 'Description 97',
      },
      {
        id: '98',
        username: 'user98',
        firstName: 'First98',
        lastName: 'Last98',
        email: 'user98@example.com',
        birthDate: '2086-02-02',
        basicSalary: 128000000,
        status: 'Fixed',
        group: 'Group ZZZZ',
        description: 'Description 98',
      },
      {
        id: '99',
        username: 'user99',
        firstName: 'First99',
        lastName: 'Last99',
        email: 'user99@example.com',
        birthDate: '2087-03-03',
        basicSalary: 129000000,
        status: 'Intern',
        group: 'Group AAAAA',
        description: 'Description 99',
      },
      {
        id: '100',
        username: 'user100',
        firstName: 'First100',
        lastName: 'Last100',
        email: 'user100@example.com',
        birthDate: '2088-04-04',
        basicSalary: 130000000,
        status: 'Fixed',
        group: 'Group BBBBB',
        description: 'Description 100',
      },
      {
        id: '101',
        username: 'user101',
        firstName: 'First101',
        lastName: 'Last101',
        email: 'user101@example.com',
        birthDate: '2060-01-01',
        basicSalary: 102000000,
        status: 'Intern',
        group: 'Group OOO',
        description: 'Description 101',
      },
      {
        id: '102',
        username: 'user102',
        firstName: 'First102',
        lastName: 'Last102',
        email: 'user102@example.com',
        birthDate: '2061-02-02',
        basicSalary: 103000000,
        status: 'Fixed',
        group: 'Group PPP',
        description: 'Description 102',
      },
      {
        id: '103',
        username: 'user103',
        firstName: 'First103',
        lastName: 'Last103',
        email: 'user103@example.com',
        birthDate: '2062-03-03',
        basicSalary: 104000000,
        status: 'Intern',
        group: 'Group QQQ',
        description: 'Description 103',
      },
      {
        id: '104',
        username: 'user104',
        firstName: 'First104',
        lastName: 'Last104',
        email: 'user104@example.com',
        birthDate: '2063-04-04',
        basicSalary: 105000000,
        status: 'Fixed',
        group: 'Group RRR',
        description: 'Description 104',
      },
      {
        id: '105',
        username: 'user105',
        firstName: 'First105',
        lastName: 'Last105',
        email: 'user105@example.com',
        birthDate: '2064-05-05',
        basicSalary: 106000000,
        status: 'Intern',
        group: 'Group SSS',
        description: 'Description 105',
      },
      {
        id: '106',
        username: 'user106',
        firstName: 'First106',
        lastName: 'Last106',
        email: 'user106@example.com',
        birthDate: '2065-06-06',
        basicSalary: 107000000,
        status: 'Fixed',
        group: 'Group TTT',
        description: 'Description 106',
      },
      {
        id: '107',
        username: 'user107',
        firstName: 'First107',
        lastName: 'Last107',
        email: 'user107@example.com',
        birthDate: '2066-07-07',
        basicSalary: 108000000,
        status: 'Intern',
        group: 'Group UUU',
        description: 'Description 107',
      },
      {
        id: '108',
        username: 'user108',
        firstName: 'First108',
        lastName: 'Last108',
        email: 'user108@example.com',
        birthDate: '2067-08-08',
        basicSalary: 109000000,
        status: 'Fixed',
        group: 'Group VVV',
        description: 'Description 108',
      },
      {
        id: '109',
        username: 'user109',
        firstName: 'First109',
        lastName: 'Last109',
        email: 'user109@example.com',
        birthDate: '2068-09-09',
        basicSalary: 110000000,
        status: 'Intern',
        group: 'Group WWW',
        description: 'Description 109',
      },
      {
        id: '110',
        username: 'user110',
        firstName: 'First110',
        lastName: 'Last110',
        email: 'user110@example.com',
        birthDate: '2069-10-10',
        basicSalary: 111000000,
        status: 'Fixed',
        group: 'Group XXX',
        description: 'Description 110',
      },
    ];
  }

  getEmployees() {
    return Promise.resolve(this.getEmployeesData());
  }
}
